In [1]:
# 1.Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

In [38]:
n = 5
np.arange((n-1),-1, -1)


array([4, 3, 2, 1, 0])

In [39]:
# 2.Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [40]:
np.diag(np.arange((n-1),-1, -1))

array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [41]:
np.sum(np.diag(np.arange((n-1),-1, -1)))

10

In [42]:
# 3.Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

In [45]:
a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])

In [46]:
from numpy import linalg

In [47]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [71]:
# 4.
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

# ответ ID8:

In [72]:
nextLength = np.linalg.norm( next_user_stats)
for el in users_stats:
    elLength = np.linalg.norm(el)
    print(np.dot( el, next_user_stats) / ( elLength * nextLength ))

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
